GET http://localhost:3000/api/dashboard/monthlysales
###
GET http://localhost:3000/api/dashboard/weeklysales
###
GET http://localhost:3000/api/dashboard/toproducts
###
GET http://localhost:3000/api/dashboard/paymentmethods
### 
GET http://localhost:3000/api/dashboard/avgproduct
###
GET http://localhost:3000/api/dashboard/avgmargin
###
GET http://localhost:3000/api/dashboard/lowproduct
###
GET http://localhost:3000/api/dashboard/categorydistribution
###
GET http://localhost:3000/api/dashboard/topsuppliers
###
GET http://localhost:3000/api/dashboard/salestrends